### ISSUE TITLE
Why there is requirement of creating an account with algobull?

### ISSUE THREAD

**Issue by muke5hy** [algobulls/pyalgotrading#4]
I do not understand, why there is a requirement of creating an account with Algobull?
Can't I use it on my own macchine?

**Comment by guanidene** [comment]
To run algorithmic trading strategies, you need a complete platform which can talk to brokers, get live datafeeds, understand the strategy working logic and much more. What we code here using pyalgotrading is just the strategy working part. The remaining platform, where your strategy would get plugged in like a gear in a gear-box, is made available by AlgoBulls as a SaaS service. To use this SaaS service, you need an AlgoBulls account.

Hope that helps.

**Comment by muke5hy** [comment]
That means one needs to purchase, even for testing and tying. It's a really bad model.  

It would be better if it can provide a mechanism to backtest locally, and then Papertrade/Live Trade on platform.

**Comment by guanidene** [comment]
The charges are required for paying the underlying historical data feeds service and broker APIs. Even if you were to build a complete algo trading platform yourself, you would still have to pay these charges yourself. And that would in fact be much more than what you have to pay for using AlgoBulls service as this is discounted due to a large customer base.

What you are looking for is like wanting to punch orders on the Stock Exchanges over APIs, but not willing to open a broking account! That's simply not possible!
